name: ci
on:
  push:
    branches:
      - master
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - uses: actions/setup-pandoc@v2
        with:
          pandoc-version: 2.19.2
      - run: pandoc --version
        env:
          PATH: ${{ steps.setup-pandoc.outputs.pandoc-path }}
      - run: pip install -r requirements.txt
      - run: mkdocs gh-deploy --force

